/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as PublierRouteImport } from './routes/publier'
import { Route as OrganisateursRouteImport } from './routes/organisateurs'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as MonEspaceRouteImport } from './routes/mon-espace'
import { Route as MesCandidaturesRouteImport } from './routes/mes-candidatures'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as BenevolesRouteImport } from './routes/benevoles'
import { Route as AnnoncesRouteImport } from './routes/annonces'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganisateursIndexRouteImport } from './routes/organisateurs.index'
import { Route as OrganisateursNosOffresRouteImport } from './routes/organisateurs.nos-offres'
import { Route as OrganisateursCommentCaMarcheRouteImport } from './routes/organisateurs.comment-ca-marche'
import { Route as ModifierAnnonceIdRouteImport } from './routes/modifier-annonce.$id'
import { Route as AnnonceIdRouteImport } from './routes/annonce.$id'
import { Route as ApiPublicQuoteRequestRouteImport } from './routes/api/public/quote-request'

const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const PublierRoute = PublierRouteImport.update({
  id: '/publier',
  path: '/publier',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateursRoute = OrganisateursRouteImport.update({
  id: '/organisateurs',
  path: '/organisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEspaceRoute = MonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => rootRouteImport,
} as any)
const MesCandidaturesRoute = MesCandidaturesRouteImport.update({
  id: '/mes-candidatures',
  path: '/mes-candidatures',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const BenevolesRoute = BenevolesRouteImport.update({
  id: '/benevoles',
  path: '/benevoles',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesRoute = AnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisateursIndexRoute = OrganisateursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganisateursRoute,
} as any)
const OrganisateursNosOffresRoute = OrganisateursNosOffresRouteImport.update({
  id: '/nos-offres',
  path: '/nos-offres',
  getParentRoute: () => OrganisateursRoute,
} as any)
const OrganisateursCommentCaMarcheRoute =
  OrganisateursCommentCaMarcheRouteImport.update({
    id: '/comment-ca-marche',
    path: '/comment-ca-marche',
    getParentRoute: () => OrganisateursRoute,
  } as any)
const ModifierAnnonceIdRoute = ModifierAnnonceIdRouteImport.update({
  id: '/modifier-annonce/$id',
  path: '/modifier-annonce/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonceIdRoute = AnnonceIdRouteImport.update({
  id: '/annonce/$id',
  path: '/annonce/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuoteRequestRoute = ApiPublicQuoteRequestRouteImport.update({
  id: '/api/public/quote-request',
  path: '/api/public/quote-request',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annonces': typeof AnnoncesRoute
  '/benevoles': typeof BenevolesRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-candidatures': typeof MesCandidaturesRoute
  '/mon-espace': typeof MonEspaceRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/organisateurs': typeof OrganisateursRouteWithChildren
  '/publier': typeof PublierRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/annonce/$id': typeof AnnonceIdRoute
  '/modifier-annonce/$id': typeof ModifierAnnonceIdRoute
  '/organisateurs/comment-ca-marche': typeof OrganisateursCommentCaMarcheRoute
  '/organisateurs/nos-offres': typeof OrganisateursNosOffresRoute
  '/organisateurs/': typeof OrganisateursIndexRoute
  '/api/public/quote-request': typeof ApiPublicQuoteRequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annonces': typeof AnnoncesRoute
  '/benevoles': typeof BenevolesRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-candidatures': typeof MesCandidaturesRoute
  '/mon-espace': typeof MonEspaceRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/publier': typeof PublierRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/annonce/$id': typeof AnnonceIdRoute
  '/modifier-annonce/$id': typeof ModifierAnnonceIdRoute
  '/organisateurs/comment-ca-marche': typeof OrganisateursCommentCaMarcheRoute
  '/organisateurs/nos-offres': typeof OrganisateursNosOffresRoute
  '/organisateurs': typeof OrganisateursIndexRoute
  '/api/public/quote-request': typeof ApiPublicQuoteRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annonces': typeof AnnoncesRoute
  '/benevoles': typeof BenevolesRoute
  '/cgu': typeof CguRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-candidatures': typeof MesCandidaturesRoute
  '/mon-espace': typeof MonEspaceRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/organisateurs': typeof OrganisateursRouteWithChildren
  '/publier': typeof PublierRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/annonce/$id': typeof AnnonceIdRoute
  '/modifier-annonce/$id': typeof ModifierAnnonceIdRoute
  '/organisateurs/comment-ca-marche': typeof OrganisateursCommentCaMarcheRoute
  '/organisateurs/nos-offres': typeof OrganisateursNosOffresRoute
  '/organisateurs/': typeof OrganisateursIndexRoute
  '/api/public/quote-request': typeof ApiPublicQuoteRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annonces'
    | '/benevoles'
    | '/cgu'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/mes-candidatures'
    | '/mon-espace'
    | '/mot-de-passe-oublie'
    | '/organisateurs'
    | '/publier'
    | '/qui-sommes-nous'
    | '/reset-password'
    | '/tableau-de-bord'
    | '/annonce/$id'
    | '/modifier-annonce/$id'
    | '/organisateurs/comment-ca-marche'
    | '/organisateurs/nos-offres'
    | '/organisateurs/'
    | '/api/public/quote-request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annonces'
    | '/benevoles'
    | '/cgu'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/mes-candidatures'
    | '/mon-espace'
    | '/mot-de-passe-oublie'
    | '/publier'
    | '/qui-sommes-nous'
    | '/reset-password'
    | '/tableau-de-bord'
    | '/annonce/$id'
    | '/modifier-annonce/$id'
    | '/organisateurs/comment-ca-marche'
    | '/organisateurs/nos-offres'
    | '/organisateurs'
    | '/api/public/quote-request'
  id:
    | '__root__'
    | '/'
    | '/annonces'
    | '/benevoles'
    | '/cgu'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/mes-candidatures'
    | '/mon-espace'
    | '/mot-de-passe-oublie'
    | '/organisateurs'
    | '/publier'
    | '/qui-sommes-nous'
    | '/reset-password'
    | '/tableau-de-bord'
    | '/annonce/$id'
    | '/modifier-annonce/$id'
    | '/organisateurs/comment-ca-marche'
    | '/organisateurs/nos-offres'
    | '/organisateurs/'
    | '/api/public/quote-request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnoncesRoute: typeof AnnoncesRoute
  BenevolesRoute: typeof BenevolesRoute
  CguRoute: typeof CguRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MesCandidaturesRoute: typeof MesCandidaturesRoute
  MonEspaceRoute: typeof MonEspaceRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  OrganisateursRoute: typeof OrganisateursRouteWithChildren
  PublierRoute: typeof PublierRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
  AnnonceIdRoute: typeof AnnonceIdRoute
  ModifierAnnonceIdRoute: typeof ModifierAnnonceIdRoute
  ApiPublicQuoteRequestRoute: typeof ApiPublicQuoteRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publier': {
      id: '/publier'
      path: '/publier'
      fullPath: '/publier'
      preLoaderRoute: typeof PublierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateurs': {
      id: '/organisateurs'
      path: '/organisateurs'
      fullPath: '/organisateurs'
      preLoaderRoute: typeof OrganisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-espace': {
      id: '/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof MonEspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-candidatures': {
      id: '/mes-candidatures'
      path: '/mes-candidatures'
      fullPath: '/mes-candidatures'
      preLoaderRoute: typeof MesCandidaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benevoles': {
      id: '/benevoles'
      path: '/benevoles'
      fullPath: '/benevoles'
      preLoaderRoute: typeof BenevolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces': {
      id: '/annonces'
      path: '/annonces'
      fullPath: '/annonces'
      preLoaderRoute: typeof AnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisateurs/': {
      id: '/organisateurs/'
      path: '/'
      fullPath: '/organisateurs/'
      preLoaderRoute: typeof OrganisateursIndexRouteImport
      parentRoute: typeof OrganisateursRoute
    }
    '/organisateurs/nos-offres': {
      id: '/organisateurs/nos-offres'
      path: '/nos-offres'
      fullPath: '/organisateurs/nos-offres'
      preLoaderRoute: typeof OrganisateursNosOffresRouteImport
      parentRoute: typeof OrganisateursRoute
    }
    '/organisateurs/comment-ca-marche': {
      id: '/organisateurs/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/organisateurs/comment-ca-marche'
      preLoaderRoute: typeof OrganisateursCommentCaMarcheRouteImport
      parentRoute: typeof OrganisateursRoute
    }
    '/modifier-annonce/$id': {
      id: '/modifier-annonce/$id'
      path: '/modifier-annonce/$id'
      fullPath: '/modifier-annonce/$id'
      preLoaderRoute: typeof ModifierAnnonceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonce/$id': {
      id: '/annonce/$id'
      path: '/annonce/$id'
      fullPath: '/annonce/$id'
      preLoaderRoute: typeof AnnonceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quote-request': {
      id: '/api/public/quote-request'
      path: '/api/public/quote-request'
      fullPath: '/api/public/quote-request'
      preLoaderRoute: typeof ApiPublicQuoteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrganisateursRouteChildren {
  OrganisateursCommentCaMarcheRoute: typeof OrganisateursCommentCaMarcheRoute
  OrganisateursNosOffresRoute: typeof OrganisateursNosOffresRoute
  OrganisateursIndexRoute: typeof OrganisateursIndexRoute
}

const OrganisateursRouteChildren: OrganisateursRouteChildren = {
  OrganisateursCommentCaMarcheRoute: OrganisateursCommentCaMarcheRoute,
  OrganisateursNosOffresRoute: OrganisateursNosOffresRoute,
  OrganisateursIndexRoute: OrganisateursIndexRoute,
}

const OrganisateursRouteWithChildren = OrganisateursRoute._addFileChildren(
  OrganisateursRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnoncesRoute: AnnoncesRoute,
  BenevolesRoute: BenevolesRoute,
  CguRoute: CguRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MesCandidaturesRoute: MesCandidaturesRoute,
  MonEspaceRoute: MonEspaceRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  OrganisateursRoute: OrganisateursRouteWithChildren,
  PublierRoute: PublierRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TableauDeBordRoute: TableauDeBordRoute,
  AnnonceIdRoute: AnnonceIdRoute,
  ModifierAnnonceIdRoute: ModifierAnnonceIdRoute,
  ApiPublicQuoteRequestRoute: ApiPublicQuoteRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
